package com.example.dllo.idealmirror.mirrordao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALL_MIRROR_CACHE".
 */
public class AllMirrorCache {

    private Long id;
    private String imgurl;
    private String goodname;
    private String productarea;
    private String brand;
    private String goodprice;
    private String goodsid;

    public AllMirrorCache() {
    }

    public AllMirrorCache(Long id) {
        this.id = id;
    }

    public AllMirrorCache(Long id, String imgurl, String goodname, String productarea, String brand, String goodprice, String goodsid) {
        this.id = id;
        this.imgurl = imgurl;
        this.goodname = goodname;
        this.productarea = productarea;
        this.brand = brand;
        this.goodprice = goodprice;
        this.goodsid = goodsid;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgurl() {
        return imgurl;
    }

    public void setImgurl(String imgurl) {
        this.imgurl = imgurl;
    }

    public String getGoodname() {
        return goodname;
    }

    public void setGoodname(String goodname) {
        this.goodname = goodname;
    }

    public String getProductarea() {
        return productarea;
    }

    public void setProductarea(String productarea) {
        this.productarea = productarea;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getGoodprice() {
        return goodprice;
    }

    public void setGoodprice(String goodprice) {
        this.goodprice = goodprice;
    }

    public String getGoodsid() {
        return goodsid;
    }

    public void setGoodsid(String goodsid) {
        this.goodsid = goodsid;
    }

}
