package com.example.dllo.idealmirror.mirrordao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "GOOD_LIST_CACHE".
 */
public class GoodListCache {

    private Long id;
    private String title;
    private String type;
    private String store;
    private String info_data;
    private String topColor;
    private String buttomColor;

    public GoodListCache() {
    }

    public GoodListCache(Long id) {
        this.id = id;
    }

    public GoodListCache(Long id, String title, String type, String store, String info_data, String topColor, String buttomColor) {
        this.id = id;
        this.title = title;
        this.type = type;
        this.store = store;
        this.info_data = info_data;
        this.topColor = topColor;
        this.buttomColor = buttomColor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getStore() {
        return store;
    }

    public void setStore(String store) {
        this.store = store;
    }

    public String getInfo_data() {
        return info_data;
    }

    public void setInfo_data(String info_data) {
        this.info_data = info_data;
    }

    public String getTopColor() {
        return topColor;
    }

    public void setTopColor(String topColor) {
        this.topColor = topColor;
    }

    public String getButtomColor() {
        return buttomColor;
    }

    public void setButtomColor(String buttomColor) {
        this.buttomColor = buttomColor;
    }

}
