package com.example.dllo.idealmirror.mirrordao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "PLAIN_MIRROR".
 */
public class PlainMirror {

    private Long id;
    private String goodsimg;
    private String goodsname;
    private String wholestorge;
    private String product;
    private String goodsprice;
    private String brand;
    private String discount;

    public PlainMirror() {
    }

    public PlainMirror(Long id) {
        this.id = id;
    }

    public PlainMirror(Long id, String goodsimg, String goodsname, String wholestorge, String product, String goodsprice, String brand, String discount) {
        this.id = id;
        this.goodsimg = goodsimg;
        this.goodsname = goodsname;
        this.wholestorge = wholestorge;
        this.product = product;
        this.goodsprice = goodsprice;
        this.brand = brand;
        this.discount = discount;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getGoodsimg() {
        return goodsimg;
    }

    public void setGoodsimg(String goodsimg) {
        this.goodsimg = goodsimg;
    }

    public String getGoodsname() {
        return goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    public String getWholestorge() {
        return wholestorge;
    }

    public void setWholestorge(String wholestorge) {
        this.wholestorge = wholestorge;
    }

    public String getProduct() {
        return product;
    }

    public void setProduct(String product) {
        this.product = product;
    }

    public String getGoodsprice() {
        return goodsprice;
    }

    public void setGoodsprice(String goodsprice) {
        this.goodsprice = goodsprice;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

    public String getDiscount() {
        return discount;
    }

    public void setDiscount(String discount) {
        this.discount = discount;
    }

}
